services:
  mysql_5:
    restart: unless-stopped
    image: mysql:5
    networks:
      private:
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./database/mysql/conf.d:/etc/mysql/conf.d:ro
      - mysql_5:/var/lib/mysql

volumes:
  mysql_5:
