services:
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    restart: always
    environment:
      WATCHTOWER_SCHEDULE: ${WATCHTOWER_SCHEDULE-0 0 17 * * *}
    healthcheck:
      interval: 1m
      timeout: 5s
      retries: 3
      start_period: 30s
      start_interval: 5s
