services:
  proxy:
    build:
      context: proxy
    restart: unless-stopped
    networks:
      - public
    ports:
        # HTTP
      - target: 80
        published: ${HTTP_PORT:-80}
        protocol: tcp
      # HTTPS
      - target: 443
        published: ${HTTPS_PORT:-443}
        protocol: tcp
      # HTTP/3
      - target: 443
        published: ${HTTP3_PORT:-443}
        protocol: udp
    environment:
      CADDY_INGRESS_NETWORKS: dev_public
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_config:/config
      - caddy_data:/data

  maildev:
    restart: always
    image: djfarrelly/maildev
    networks:
      public:
      private:
    environment:
      VIRTUAL_HOST: maildev.${DOCKER_HOST_SUFFIX:-local}
    command: bin/maildev --web 80 --smtp 25 --outgoing-host smtp-relay.gmail.com --outgoing-secure --hide-extensions STARTTLS

  memcached:
    restart: always
    image: memcached:1.4
    networks:
      private:

networks:
    public:
        driver: bridge
    private:
        driver: bridge

volumes:
    ssl-certs:
    caddy_data:
    caddy_config:
