version: '2'

services:
    proxy:
        restart: unless-stopped
        image: jwilder/nginx-proxy
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
            - ./conf/ssl/certs:/etc/nginx/certs:ro
            - ./conf/proxy/default.conf:/etc/nginx/proxy.conf
        networks:
            - proxy
        ports:
            - '80:80'
            - '443:443'

    adminer:
        restart: unless-stopped
        image: dehy/adminer
        environment:
            VIRTUAL_HOST: adminer.docker, adminer.$DOCKER_HOST_SUFFIX
        networks:
            - proxy
            - database

    pgsql_94:
        restart: unless-stopped
        image: postgres:9.4
        networks:
            - database
        volumes:
            - pgsql_94_data:/var/lib/postgres/data
        environment:
            PGDATA: /var/lib/postgres/data

    pgsql_95:
        restart: unless-stopped
        image: postgres:9.5
        networks:
            - database
        volumes:
            - pgsql_95_data:/var/lib/postgres/data
        environment:
            PGDATA: /var/lib/postgres/data

    mysql_55:
        restart: unless-stopped
        image: mysql:5.5
        networks:
            - database
        environment:
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./conf/mysql/conf.d:/etc/mysql/conf.d:ro
            - mysql_55_data:/var/lib/mysql

    mysql_57:
        restart: unless-stopped
        image: mysql:5.7
        networks:
            - database
        environment:
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./conf/mysql/conf.d:/etc/mysql/conf.d:ro
            - mysql_57_data:/var/lib/mysql

    maildev:
        restart: unless-stopped
        image: djfarrelly/maildev
        networks:
            - proxy
            - maildev
        environment:
            VIRTUAL_HOST: maildev.docker, maildev.$DOCKER_HOST_SUFFIX
        command: bin/maildev --web 80 --smtp 25 --outgoing-host smtp-relay.gmail.com --outgoing-secure

    memcached:
        restart: unless-stopped
        image: memcached:1.4
        networks:
            - memcached

networks:
    proxy:
        driver: bridge
    maildev:
        driver: bridge
    database:
        driver: bridge
    memcached:
        driver: bridge

volumes:
    mysql_57_data:
        driver: local
    mysql_55_data:
        driver: local
    pgsql_95_data:
        driver: local
    pgsql_94_data:
        driver: local
