version: '3.2'

services:
    proxy:
        restart: unless-stopped
        image: jwilder/nginx-proxy
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
            - ./conf/ssl/certs:/etc/nginx/certs:ro
            - ./conf/proxy/default.conf:/etc/nginx/proxy.conf
        networks:
            - proxy
        ports:
            - '80:80'
            - '443:443'

    adminer:
        restart: unless-stopped
        image: dehy/adminer
        environment:
            VIRTUAL_HOST: adminer.${DOCKER_HOST_SUFFIX:-docker}, *.adminer.${DOCKER_HOST_SUFFIX:-docker}
        networks:
            - proxy
            - database

    maildev:
        restart: unless-stopped
        image: djfarrelly/maildev
        networks:
            - proxy
            - maildev
        environment:
            VIRTUAL_HOST: maildev.${DOCKER_HOST_SUFFIX:-docker}
        command: bin/maildev --web 80 --smtp 25 --outgoing-host smtp-relay.gmail.com --outgoing-secure

    memcached:
        restart: unless-stopped
        image: memcached:1.4
        networks:
            - memcached

    docs:
        image: clue/sculpin
        command: generate --watch --server
        networks:
            - proxy
        volumes:
            - ./docs:/data
        environment:
            VIRTUAL_HOST: docs.${DOCKER_HOST_SUFFIX:-docker}
            VIRTUAL_PORT: 8000

networks:
    proxy:
        driver: bridge
    maildev:
        driver: bridge
    database:
        driver: bridge
    memcached:
        driver: bridge
