version: "3.2"

services:
    proxy:
        restart: always
        image: nginxproxy/nginx-proxy
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
            - ssl-certs:/etc/nginx/certs:ro
            - ./conf/proxy/default.conf:/etc/nginx/proxy.conf
        networks:
            proxy:
        labels:
            - com.github.aegypius.mkcert-for-nginx-proxy.nginx_proxy
        ports:
            - "80:80"
            - "443:443"

    mkcert:
        container_name: mkcert-for-nginx-proxy
        image: registry.gitlab.com/lephare/docker-stack/mkcert-for-nginx-proxy
        restart: always
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - ssl-certs:/app/certs:rw
            - ~/.mozilla/firefox:/root/.mozilla/firefox
            - ~/.pki/nssdb:/root/.pki/nssdb
            - ${CA_STORE:-/usr/local/share/ca-certificates}:/usr/local/share/ca-certificates

    maildev:
        restart: always
        image: djfarrelly/maildev
        networks:
            proxy:
            maildev:
        environment:
            VIRTUAL_HOST: maildev.${DOCKER_HOST_SUFFIX:-local}
        command: bin/maildev --web 80 --smtp 25 --outgoing-host smtp-relay.gmail.com --outgoing-secure --hide-extensions STARTTLS

    memcached:
        restart: always
        image: memcached:1.4
        networks:
            memcached:

networks:
    proxy:
        driver: bridge
    maildev:
        driver: bridge
    database:
        driver: bridge
    memcached:
        driver: bridge

volumes:
    ssl-certs:
