version: '2'

services:
    elastic_53:
        image: docker.elastic.co/elasticsearch/elasticsearch:5.3.0
        environment:
            http.host: 0.0.0.0
            transport.host: 127.0.0.1
            xpack.security.enabled: "false"
            ES_JAVA_OPTS: "-Xms256m -Xmx256m"
        volumes:
            - es_data:/usr/share/elasticsearch/data
        mem_limit: 1g

volumes:
    es_data:
        driver: local
