version: '3.2'

services:
    elastic_53:
        image: docker.elastic.co/elasticsearch/elasticsearch:5.3.0
        networks:
            - database
        environment:
            http.host: 0.0.0.0
            transport.host: 127.0.0.1
            xpack.security.enabled: "false"
            ES_JAVA_OPTS: "-Xms256m -Xmx256m"
        volumes:
            - es_data:/usr/share/elasticsearch/data

volumes:
    es_data:
        driver: local
