version: '3.2'

services:
    mysql_55:
        restart: unless-stopped
        image: mysql:5.5
        networks:
            - database
        environment:
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./conf/mysql/conf.d:/etc/mysql/conf.d:ro
            - mysql_55_data:/var/lib/mysql

volumes:
    mysql_55_data:
        driver: local
