version: '2'

services:
    pgsql_96:
        restart: unless-stopped
        image: postgres:9.6
        networks:
            - database
        volumes:
            - pgsql_96_data:/var/lib/postgres/data
        environment:
            PGDATA: /var/lib/postgres/data

volumes:
    pgsql_96_data:
        driver: local
