version: '2'

services:
    pgsql_94:
        restart: unless-stopped
        image: postgres:9.4
        networks:
            - database
        volumes:
            - pgsql_94_data:/var/lib/postgres/data
        environment:
            PGDATA: /var/lib/postgres/data

volumes:
    pgsql_94_data:
        driver: local
