version: '3.2'

services:
    pgsql_95:
        restart: unless-stopped
        image: postgres:9.5
        networks:
            - database
        volumes:
            - pgsql_95_data:/var/lib/postgres/data
        environment:
            PGDATA: /var/lib/postgres/data

volumes:
    pgsql_95_data:
        driver: local
