redis:
    image: redis:latest
    expose:
        - 6379
    volumes:
        - /tmp/redis:/data


mongodb:
    image: mongo:latest
    command: mongod --smallfiles --directoryperdb --noprealloc
    hostname: mongodb
    volumes:
        - /tmp/mongodb:/data/db
    expose:
        - 27017

semaphore:
    image: castawaylabs/semaphore:latest
    environment:
        MONGODB_URL: mongodb://mongodb/semaphore
        REDIS_HOST: redis
        VIRTUAL_HOST: semaphore.docker
    ports:
        - 80
    links:
        - redis:redis
        - mongodb:mongodb
