version: '3.2'

services:
    adminer:
        restart: unless-stopped
        image: dehy/adminer
        environment:
            VIRTUAL_HOST: adminer.lephare-systeme.com
            LETSENCRYPT_HOST: adminer.lephare-systeme.com
            LETSENCRYPT_EMAIL: $LETSENCRYPT_EMAIL
        networks:
            - proxy
            - database

networks:
    database: ~
