version: '3.2'

services:
    nginx:
        container_name: nginx
        image: nginx
        restart: unless-stopped
        ports:
            - '80:80'
            - '443:443'
        networks:
            - proxy
        volumes:
            - nginx-htpasswd:/etc/nginx/passwd
            - nginx-conf.d:/etc/nginx/conf.d
            - nginx-vhost.d:/etc/nginx/vhost.d
            - nginx-html:/usr/share/nginx/html
            - ssl-certs:/etc/nginx/certs:ro
        labels:
            com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: nginx

    nginx-gen:
        container_name: nginx-gen
        image: jwilder/docker-gen
        restart: unless-stopped
        networks:
            - proxy
        volumes:
            - nginx-htpasswd:/etc/nginx/passwd
            - nginx-conf.d:/etc/nginx/conf.d
            - nginx-vhost.d:/etc/nginx/vhost.d
            - nginx-html:/usr/share/nginx/html
            - ssl-certs:/etc/nginx/certs:ro
            - docker-gen-tmpl:/etc/docker-gen/templates
            - /var/run/docker.sock:/tmp/docker.sock:ro
        command: -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
        labels:
            com.github.jrcs.letsencrypt_nginx_proxy_companion.docker_gen: jwilder/docker-gen

    letsencrypt:
        container_name: letsencrypt
        image:  jrcs/letsencrypt-nginx-proxy-companion
        restart: unless-stopped
        depends_on:
            - nginx
            - nginx-gen
        volumes:
            - nginx-htpasswd:/etc/nginx/passwd
            - nginx-conf.d:/etc/nginx/conf.d
            - nginx-vhost.d:/etc/nginx/vhost.d
            - nginx-html:/usr/share/nginx/html
            - ssl-certs:/etc/nginx/certs:rw
            - /var/run/docker.sock:/var/run/docker.sock:ro
        environment:
            NGINX_DOCKER_GEN_CONTAINER: nginx-gen

    watchtower:
        container_name: watchtower
        image: v2tec/watchtower
        restart: always
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        command: --interval 30 --cleanup

networks:
    proxy:
        driver: bridge

volumes:
    nginx-conf.d: ~
    nginx-vhost.d: ~
    nginx-htpasswd: ~
    nginx-html: ~
    docker-gen-tmpl:
        external: true
    ssl-certs:
        external: true
