services:
  pgsql_14:
    restart: unless-stopped
    image: postgres:14
    networks:
      private:
    volumes:
      - pgsql_14:/var/lib/postgres/data
    environment:
      PGDATA: /var/lib/postgres/data
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      timeout: 5s
      start_period: 10s

volumes:
  pgsql_14:
