version: '2'

services:
    nginx:
        container_name: nginx
        image: nginx
        restart: unless-stopped
        ports:
            - '80:80'
            - '443:443'
        networks:
            - proxy
        volumes:
            - /etc/nginx/conf.d
            - /etc/nginx/vhost.d
            - /usr/share/nginx/html
            - ssl-certs:/etc/nginx/certs:ro

    nginx-gen:
        container_name: nginx-gen
        build: nginx-gen
        restart: unless-stopped
        networks:
            - proxy
        volumes_from:
            - nginx
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
        command: -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf

    letsencrypt:
        container_name: letsencrypt
        image:  jrcs/letsencrypt-nginx-proxy-companion
        restart: unless-stopped
        volumes_from:
            - nginx
        volumes:
            - ssl-certs:/etc/nginx/certs:rw
            - /var/run/docker.sock:/var/run/docker.sock:ro
        environment:
            NGINX_DOCKER_GEN_CONTAINER: nginx-gen

    # dl:
    #     image: quay.io/aegypius/statik
    #     restart: unless-stopped
    #     networks:
    #         - proxy
    #     environment:
    #         VIRTUAL_HOST: dl.lephare-systeme.com
    #         LETSENCRYPT_HOST: dl.lephare-systeme.com
    #         LETSENCRYPT_EMAIL: systeme@lephare.com

    toran_web:
        image: lephare/apache:2.4
        networks:
            - proxy
            - toran
        environment:
            VIRTUAL_HOST: toran.lephare-systeme.com
            LETSENCRYPT_HOST: toran.lephare-systeme.com
            LETSENCRYPT_EMAIL: systeme@lephare.com
            DOCUMENT_ROOT: /app/web
            APACHE_LOG_PREFIX: toran-proxy
        volumes_from:
            - php
        volumes:
            - apache-logs:/var/log/apache2

    php:
        image: lephare/toran-proxy
        volumes:
            - /app/web
            - toran-data:/data:rw
        networks:
            - toran
        environment:
            TORAN_TOKEN_GITHUB: 36ccc30e9e870bd65b80f161dc1b81389dd8b354

networks:
    proxy:
        driver: bridge
    toran:
        driver: bridge

volumes:
    ssl-certs:
        external: true
    toran-data:
        external: true
    apache-logs:
        external: true
