nginx:
    image: nginx
    restart: unless-stopped
    ports:
        - 80:80
        - 443:443
    volumes:
        - /etc/nginx/conf.d
        - /etc/nginx/vhost.d
        - /usr/share/nginx/html
        - ssl-certs:/etc/nginx/certs:ro

nginx-gen:
    build: nginx-gen
    restart: unless-stopped
    volumes_from:
        - nginx
    volumes:
        - /var/run/docker.sock:/tmp/docker.sock:ro
    command: -notify-sighup lepharesysteme_nginx_1 -watch -only-exposed -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf

letsencrypt:
    image:  jrcs/letsencrypt-nginx-proxy-companion
    restart: unless-stopped
    volumes_from:
        - nginx
    volumes:
        - ssl-certs:/etc/nginx/certs:rw
        - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
        NGINX_DOCKER_GEN_CONTAINER: lepharesysteme_nginx-gen_1

dl:
    image: quay.io/aegypius/statik
    restart: unless-stopped
    environment:
        VIRTUAL_HOST: dl.lephare-systeme.com
        LETSENCRYPT_HOST: dl.lephare-systeme.com
        LETSENCRYPT_EMAIL: systeme@lephare.com
