storage:
    image: busybox:latest
    volumes:
        - ./storage/consul:/data
    command: rm -fvr /data/services/*

consul:
    build: ./consul
    command: consul agent -config-dir=/config -server -bootstrap -dc srvproxy -advertise 192.168.1.13
    volumes:
        - ./storage/consul/raft:/data/raft
        - ./storage/consul/serf:/data/serf
    ports:
        - "8300:8300"
        - "8400:8400"
        - "8500:8500"
        - "8600:53/udp"

registrator:
    build: ./registrator
    command: registrator consul://consul:8500
    links:
        - consul
    volumes:
        - "/var/run/docker.sock:/tmp/docker.sock"

lb:
    build: ./load-balancer
    command: consul-template --config /etc/consul-template/config.hcl --consul=consul:8500
    links:
        - consul
    ports:
        - "80:80"

mailcatcher:
    image: aegypius/mailcatcher:latest
    environment:
        SERVICE_1080_NAME: http
        SERVICE_TAGS: mailcatcher
    ports:
        - "8025:1025"
        - "1080"

redisui:
    build: redis-commander
    environment:
        - SERVICE_8081_NAME=http
        - SERVICE_TAGS=redis
    links:
        - redis
    ports:
        - "8081"

redis:
    image: redis:latest
    environment:
        SERVICE_NAME: redis
    volumes:
        - ./storage/redis:/data
    ports:
        - "6379:6379"
