services:
  mysql_5:
    restart: unless-stopped
    image: mysql:5-debian
    networks:
      private:
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./database/mysql/conf.d:/etc/mysql/conf.d:ro
      - mysql_5:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 1m
      timeout: 5s
      retries: 3
      start_period: 30s
      start_interval: 5s
    # see https://github.com/docker-library/mysql/issues/579#issuecomment-519495808
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

volumes:
  mysql_5:
