services:
    pgsql_14:
        restart: unless-stopped
        image: postgres:14
        networks:
            backend:
        volumes:
            - pgsql_14_data:/var/lib/postgres/data
        environment:
            PGDATA: /var/lib/postgres/data
            POSTGRES_PASSWORD: root

volumes:
    pgsql_13_data:
        driver: local
