services:
  pgsql_14:
    restart: unless-stopped
    image: postgres:14
    networks:
      private:
    volumes:
      - pgsql_14:/var/lib/postgres/data
    environment:
      PGDATA: /var/lib/postgres/data
      POSTGRES_PASSWORD: root
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 1ms
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  pgsql_14:
