services:
  pgsql_9:
    image: postgres:9
    restart: unless-stopped
    networks:
      private:
    volumes:
      - pgsql_9:/var/lib/postgres/data
    environment:
      PGDATA: /var/lib/postgres/data
      POSTGRES_PASSWORD: root

volumes:
  pgsql_9:
