services:
  adminer:
    restart: always
    image: adminer
    labels:
      caddy: adminer.${DOCKER_HOST_SUFFIX:-local}
      caddy.tls: internal
      caddy.reverse_proxy: "{{upstreams 8080}}"
    networks:
      public:
      private:
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 1ms
      timeout: 5s
      retries: 5
      start_period: 30s
