services:
  adminer:
    restart: always
    image: adminer
    labels:
      caddy: adminer.${DOCKER_HOST_SUFFIX:-local}
      caddy.tls: internal
      caddy.reverse_proxy: "{{upstreams 8080}}"
    networks:
      public:
      private:
    healthcheck:
      test: ["CMD", "php", "-r", "@file_get_contents('http://localhost:8080') or exit(1);"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
