services:
  adminer:
    restart: unless-stopped
    image: adminer:4
    volumes:
      - "./database/adminer/plugins/le-phare-pre-login-to-databases.php:/var/www/html/plugins/le-phare-pre-login-to-databases.php:ro"
    networks:
      - private
      - public
    command: "php -S [::]:80 -t /var/www/html"
    labels:
      caddy: adminer.${DOCKER_HOST_SUFFIX:-local}
      caddy.tls: internal
      caddy.reverse_proxy: "{{ upstreams }}"
    environment:
      ADMINER_PLUGINS: le-phare-pre-login-to-databases
